# =============================================================================
# DEMO CONFIGURATION - FOR SYSTEM DEMONSTRATION ONLY
# =============================================================================
# This demo uses a small dataset (100 rows) to illustrate system basics.
#
# For production use with meaningful results:
#   - Minimum: 100,000 rows of data
#   - Recommended: 1,000,000+ rows
#
# See the main config.yaml and input_schemas.yaml for production templates.
# =============================================================================

project_settings:
  project_file_path: "./examples/"
  output_file_name: "demo_training_log.txt"
  model_file_name: "output/demo_model.pth"
  create_new_model: 1
  save_model: 0  # Don't save this demo model
  device: cpu

data_splitting:
  validation_size: 0.2
  num_validation_files: 0

training_parameters:
  batch_size: 4
  block_size: 4
  max_iters: 50  # Very short training for demo
  eval_interval: 25
  learning_rate: 0.001

model_architecture:
  n_embd: 32
  n_head: 4
  n_layer: 2
  dropout: 0.1
