# =============================================================================
# EXAMPLE 1: BASIC MULTIMODAL CONFIGURATION
# =============================================================================
# This is a beginner-friendly example demonstrating a simple multimodal setup
# with 4 modalities using a single data file. Perfect for learning the basics!
#
# Features demonstrated:
# - Multiple modalities from one data source
# - Basic data processing functions
# - Cross-attention between modalities
# - Small model for fast training
# - CPU-friendly settings

# =============================================================================
# PROJECT SETTINGS
# =============================================================================
project_settings:
  # Main project directory - change this to your project path
  project_file_path: "./examples/"

  # Output file for training logs and results
  output_file_name: "basic_example_training_log.txt"

  # Model file name for saving/loading trained models
  model_file_name: "output/basic_example_model.pth"

  # Model creation and saving behavior:
  # 1 = Create new model (recommended for examples)
  # 0 = Load existing model
  create_new_model: 1

  # Model saving behavior:
  # 1 = Save model during training and at completion
  # 0 = Don't save model (training session only)
  save_model: 1

  # Training device - options: 'cpu', 'cuda', 'auto'
  # 'cpu' is recommended for this small example
  device: cpu

# =============================================================================
# DATA SPLITTING
# =============================================================================
data_splitting:
  # Use 20% of data for validation (larger split for small dataset)
  validation_size: 0.2

  # Number of files to use for validation (0 = use validation_size instead)
  num_validation_files: 0

# =============================================================================
# TRAINING PARAMETERS
# =============================================================================
# Small, fast settings perfect for learning and quick experimentation
training_parameters:
  # Number of examples processed together
  # Small batch size for this example
  batch_size: 4

  # Context window size - how many time steps the model sees at once
  # Small for this example dataset
  block_size: 8

  # Maximum training iterations (epochs)
  # Low number for quick demonstration
  max_iters: 100

  # How often to evaluate on validation set
  # Frequent evaluation for monitoring
  eval_interval: 25

  # Learning rate - how fast the model learns
  # Standard rate suitable for most cases
  learning_rate: 0.001

# =============================================================================
# MODEL ARCHITECTURE
# =============================================================================
# Small model architecture for fast training and low resource usage
model_architecture:
  # Embedding dimension - internal representation size
  # Small for this example
  n_embd: 32

  # Number of attention heads
  # Must divide evenly into n_embd (32/4 = 8)
  n_head: 4

  # Number of transformer layers
  # Few layers for simplicity
  n_layer: 2

  # Dropout rate for regularization
  # Low dropout for small model
  dropout: 0.1